pythonProject/mysite/main/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

from main import views


urlpatterns = [
    path('', views.index, name='home'),
    path('contacts/', views.contacts, name='contacts'),
    #path('news/', views.news_home, name='news'),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

pythonProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    #path('accounts', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/mysite/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import profile_view

app_name = 'users'

urlpatterns = [
    path('login',views.login_view, name='login'),
    path('logout',views.logout_view, name='logout'),
    path('register', views.register_view, name="register"),
    path('profile/', views.profile_view, name='profile'),
    path('profile/change_password/', views.change_password_view, name='change_password'),

#path('home/',views.index),
#path('contacts/',views.contacts),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/mysite/main/models.py
from django.db import models

# Create your models here.

pythonProject/mysite/main/views.py
from django.shortcuts import render
from news.models import Articles


# Create your views here.
def index(request):
    articles = Articles.objects.order_by('-date')[:3]  # Получаем три последние новости
    return render(request, 'main/index.html', {'articles': articles})

def contacts(request):
    return render(request, 'main/contacts.html')
def news_home(request):
    return render(request, 'news/templates/news/news_home.html')

pythonProject/mysite/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns:main="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{%static 'main/css/main.css' %}">
  {% block css %}
    {% endblock css %}
     {% block title %}
    {% endblock title %}
</head>

<body>
    <div id="page" class="container">
<header>
<div class="header-container">

    <h4>ПГТ Мочалкино</h4>
    <nav>
			<a href="{% url 'home' %}" accesskey="1" title="">Главная</a>
				<a href="{% url 'news' %}" accesskey="2" title="">Новости</a>
				<a href="{% url 'contacts' %}" accesskey="3" title="">Контакты</a>
                {% if user.is_authenticated %}
        {% if user.is_staff %}
                   <a href="{% url 'create' %}" accesskey="4" title="">Добавить новость</a>
        {% endif %}
        <a href="{% url 'users:profile' %}">Профиль</a>
                 <form class="logout" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                                       <button class="button-link">Выход</button>
                    </form>

                {% else %}
              <a href="{% url 'users:register' %}" accesskey="5" title="">Регистрация</a>
                <a href="{% url 'users:login' %}" accesskey="6" title="">Вход</a>
                {% endif %}
                    <div class="search-container"><form  action="{% url 'search' %}" method="get">
        <input type="text" name="query" placeholder="Поиск">
        <button type="submit" class="button-link" >Search</button>
      </form></div>
    </nav>
    </div>
		</header>
    </div>
  {% block container %}


    {% endblock container %}


</body>

pythonProject/mysite/main/templates/main/contacts.html
<!DOCTYPE html>
<html lang="en">
{% extends "main/base.html" %}
{% load static %}
{% block css %} {% endblock css %}
    <title>Home</title>

{% block container %}
<div id="page" class="container">
            <div class="info-block">
    <p>Привет, мы -  Федорова В.А. и Григорян Д.А., и мы делали этот сайт.
</p></div>
    </div>
{% endblock container%}

pythonProject/mysite/main/templates/main/dropdown.html
<!DOCTYPE html>
<html lang="en">
<li class="dropdown">
  <a href="#">Категории</a>
  <ul class="dropdown__menu">
    {% recursetree list_category %}
      <li>
        <a href="{% url 'post_list' node.slug %}">{{ node.name }}</a>
        {% if not node.is_leaf_node %}
          <ul class="children">
            {{ children }}
          </ul>
        {% endif %}
      </li>
    {% endrecursetree %}
  </ul>
</li>

pythonProject/mysite/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}
{% block css %} {% endblock css %}
   {% block title %} <title>Home</title>{% endblock title %}

{% block container %}
<br>
	<h1 align="middle">О нас</h1>
<div class="wrapper">
<div id="page" class="container">

	{% if user.is_authenticated %}
        <p>Welcome {{ user.username }} !!!</p>
    {% endif %}
    <main>
		<div class="column">
			<div class="title">
				<h2>НАШ МАЛЕНЬКИЙ УГОЛОК</h2>
			</div>
			<p>ПГТ Мочалкино находится в Псковской области. Наше население на дату 14.06.2024 составляет 3500 человек. </p>
		</div>
		<div class="column">
			<div class="title">
				<h2>КАК СДЕЛАТЬ ШАШЛЫК НА БАЛКОНЕ ПРАВИЛЬНО</h2>
			</div>
			<img src="https://sun9-77.userapi.com/impg/zF_zOgJzhGWOlvBcBeHXWkOtgHZ83naEKdAkoA/QX0xcVBpMi4.jpg?size=736x769&quality=95&sign=98cadd3d28c49dc5d219848483a0d4f8&type=album" width="282" height="150" alt="" />
			<p> Наступило лето, но нет возможности сорваться с друзьями за город? Расскажем о способах полакомиться любимой едой, не выходя из дома и не привлекая внимания пожарных.</p>
		</div>
		<div class="column">
			<div class="title">
				<h2>ВЫБИРАЕМ ШОППЕРЫ ДЛЯ ПОКУПКИ КАРТОШКИ</h2>
			</div>
			<img src="https://sun9-33.userapi.com/impg/kuvpbZa52lwhUdqqVwKdbMZU1MFZTeAZnqBwVA/Tm_ATMy9YVU.jpg?size=736x981&quality=95&sign=c31c6670ee8737aaf17682874fcfb78a&type=album" width="282" height="150" alt="" />
			<p>Мы расскажем о практических способах ходить за картошкой с любимой сумочкой, не пачкая её.</p>
		</div>
		<div class="column">
			<div class="title">
				<h2>ОФОРМЛЯЕМ ДОМ СТИЛЬНО</h2>
			</div>
			<img src="http://rasfokus.ru/images/photos/medium/074021192cd937c16471aca7e5773ea6.jpg" width="282" height="150" alt="" />
			<p>Раскрошившиеся наличники - не приговор, и теперь вы сможете оформить свой маленький уголок красиво.</p>
		</div>
		    </main>
<br>
	<h1 align="middle">Последние новости</h1>
    <div class="info-block">

        {% for article in articles %}
            <li>
                <h2><strong><a style="color: white; text-align:center;text-decoration: none; font-weight: 800; padding-bottom: 20px;" href="{% url 'news_detail' article.id %}">{{ article.title }}</a></strong></h2>
                <p>{{ article.summary }}</p>
                <p>Published on: {{ article.date }}</p>
            </li>
        {% endfor %}

		</div>
			</div>
{% endblock container%}