pythonProject/mysite/main/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

from main import views


urlpatterns = [
    path('', views.index, name='home'),
    path('contacts/', views.contacts, name='contacts'),
    #path('news/', views.news_home, name='news'),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

pythonProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('news/', include('news.urls')),
    path('users/', include('users.urls')),
    #path('accounts', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/mysite/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import profile_view

app_name = 'users'

urlpatterns = [
    path('login',views.login_view, name='login'),
    path('logout',views.logout_view, name='logout'),
    path('register', views.register_view, name="register"),
    path('profile/', views.profile_view, name='profile'),
    path('profile/change_password/', views.change_password_view, name='change_password'),

#path('home/',views.index),
#path('contacts/',views.contacts),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/mysite/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

#class User(AbstractUser):
    #pass

pythonProject/mysite/users/forms.py
from django import forms


class LoginUserForm(forms.Form):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={
        'class': 'form-input'
    }))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={
        'class': 'form-input'
    }))

pythonProject/mysite/users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm

from news.models import Comments


# Create your views here.

@login_required
def profile_view(request):
    author = request.user
    comments = Comments.objects.filter(author=author)  # Замените на ваш способ получения комментариев пользователя
    context = {
        'user': author,
        'comments': comments,
    }
    return render(request, 'users/profile.html', context)

@login_required
def change_password_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Обновление сессии пользователя
            messages.success(request, 'Пароль успешно изменён!')
            return redirect('home')
        else:
            messages.error(request, 'Ошибка. Измените данные.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/change_password.html', {'form': form})

#def logout_user(request):
#return HttpResponse("logout")
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            #form.save()
            return HttpResponseRedirect(reverse('home'))
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", {"form": form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return HttpResponseRedirect(reverse('home'))
    else:
        form = AuthenticationForm()
        return render(request, "users/login.html", {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return HttpResponseRedirect(reverse('home'))

# cd = form.cleaned_data
# user = authenticate(request, username=cd['username'],
# password=cd['password'])
# if user and user.is_active:

pythonProject/mysite/users/templates/users/change_password.html
{% extends "main/base.html" %}

{% block title %} <title>Смена пароля</title>{% endblock title %}
{% block container %}
<div id="page" class="container">
  <h1>Смена пароля</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить</button>
  </form>
{% endblock container %}

pythonProject/mysite/users/templates/users/login.html
{% extends "main/base.html" %}

{% block title %} <title>Авторизация</title>{% endblock title %}
{% block container %}
<div id="page" class="container">
                      <div class="info-block">
    <h1>Авторизация</h1>
    <form action="login" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Войти</button></p>
</div>
    </div>
</form>
{% endblock container %}

pythonProject/mysite/users/templates/users/profile.html
{% extends "main/base.html" %}

{% block title %} <title>Регистрация</title>{% endblock title %}
{% block container %}
<div class="container">
                  <div class="info-block">
  <h3>Профиль</h3>
   <br>
  <br>
  <h5>Информация о пользователе</h5>

  <p>Username: {{ user.username }}</p>


  <h5>Комментарии</h5>
  <ul>
    {% for comment in comments %}
      <li>{{ comment.full_text}}</li>
    {% empty %}
      <li>No comments yet.</li>
    {% endfor %}
  </ul>

    <h3>Смена пароля</h3>
  <a href="{% url 'users:change_password' %}">Сменить</a>
</div>
</div>
</div>
{% endblock container %}

pythonProject/mysite/users/templates/users/register.html
{% extends "main/base.html" %}

{% block title %} <title>Регистрация</title>{% endblock title %}
{% block container %}
<div id="page" class="container">
                          <div class="info-block">
    <div class="row justify-content-center">
        <h1>Регистрация</h1>
          <form action="register" method="post">
         {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Зарегистрироваться</button></p>
</div>
                              </div>
</form>
{% endblock container %}